export const actionType = {
  UPDATE_DOCUMENTATION: "UPDATE_DOCUMENTATION",
  UPDATE_LEARN_SCENE: "UPDATE_LEARN_SCENE",
  UPDATE_ARTICLES: "UPDATE_ARTICLES",
  UPDATE_ARTICLES_SCENE: "UPDATE_ARTICLES_SCENE",
  GET_FAQ_DATA: "GET_FAQ_DATA",
};
