export const actionType = {
  UPDATE_DOCUMENTATION: "UPDATE_DOCUMENTATION",
  UPDATE_LEARN_SCENE: "UPDATE_LEARN_SCENE",
  UPDATE_ARTICLES: "UPDATE_ARTICLES",
  UPDATE_ARTICLES_SCENE: "UPDATE_ARTICLES_SCENE",
  UPDATE_PROJECTS: "UPDATE_PROJECTS",
  UPDATE_PROJECTS_SCENE: "UPDATE_PROJECTS_SCENE",
  UPDATE_LANDING_SCENE: "UPDATE_LANDING_SCENE",
  UPDATE_SETTINGS: "UPDATE_SETTINGS",
  UPDATE_LAYOUT: "UPDATE_LAYOUT",
};
