version: "3"
services:
  postgress:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: db

  meilisearch:
    image: getmeili/meilisearch:v1.13
    ports:
      - "7700:7700"
    volumes:
      - ./meilisearch_db:/meili_data
    environment:
      MEILI_NO_ANALYTICS: true
      MEILI_MASTER_KEY: "default"
