name: Deploy To Stage Environment

on:
  push:
    tags:
      - "stg-v*"
    branches:
      - chore/monorepo-setup

jobs:
  install-build-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest]

    steps:
      - name: "Git"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Nodejs"
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: "Install"
        shell: bash
        run: |
          yarn --frozen-lockfile --network-timeout 1000000

      - name: "Build"
        shell: bash
        run: |
          yarn build

      - name: "Deploy"
        shell: bash
        run: |
          yarn deploy:stg

        env:
          CI: true
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
