name: "Web Checks"

on:
  pull_request:
    paths:
      - ".github/workflows/check-web.yml"
      - "common/**"
      - "web/**"

jobs:
  Web-Check:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x]
        os: [macos-latest, ubuntu-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install workspace dependencies"
        run: |
          yarn --frozen-lockfile
      - name: "checking script in web directory"
        run: |
          cd web
          yarn common:sync
          yarn lint:check
          yarn test:cov
          yarn build
          yarn generate:sitemap

        env:
          CI: true
