name: "Common Checks"

on:
  pull_request:
    paths:
      - ".github/workflows/check-common.yml"
      - "common/**"

jobs:
  Common-Check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install workspace dependencies"
        run: |
          yarn
      - name: "checking script in common directory"
        run: |
          cd common
          yarn lint:check
          yarn test:cov
          yarn build

        env:
          CI: true
