name: "Mobile Checks"

on:
  pull_request:
    paths:
      - ".github/workflows/check-mobile.yml"
      - "common/**"
      - "mobile/**"

jobs:
  Mobile-Check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install workspace dependencies"
        run: |
          yarn
      - name: "Build common directory"
        run: |
          cd common
          yarn build
      - name: "Install mobile dependencies"
        run: |
          cd mobile
          yarn
      - name: "checking script in mobile directory"
        run: |
          cd mobile
          yarn lint:check
          yarn test:cov

        env:
          CI: true
