name: "Api Checks"

on:
  pull_request:
    paths:
      - ".github/workflows/check-api.yml"
      - "common/**"
      - "api/**"

jobs:
  Api-Check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install workspace dependencies"
        run: |
          yarn
      - name: "checking script in api directory"
        run: |
          cd api
          yarn common:sync
          yarn lint:check
          yarn test:cov
          yarn build

        env:
          CI: true
