name: "Data Checks"

on:
  pull_request:
    paths:
      - ".github/workflows/check-data.yml"
      - "common/**"
      - "data/**"

jobs:
  Data-Check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install workspace dependencies"
        run: |
          yarn
      - name: "Build common directory"
        run: |
          cd common
          yarn build
      - name: "checking script in data directory"
        run: |
          cd data
          yarn lint:check
          yarn test:cov
          yarn build
          yarn generate:data

        env:
          CI: true
