name: "Tests"

on:
  push:
    branches:
      - master

jobs:
  Tests-Upload-Coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Running Tests with Coverage Report"
        run: |
          yarn
          yarn test:cover

      - name: Upload Fullstack Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: fullstack
          name: codecov-fullstack
          directory: ./fullstack
          fail_ci_if_error: true
        env:
          CI: true

      - name: Upload Frontend Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: frontend
          name: codecov-frontend
          directory: ./frontend
          fail_ci_if_error: true
        env:
          CI: true

      - name: Upload Data Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: data
          name: codecov-data
          directory: ./data
          fail_ci_if_error: true
        env:
          CI: true
