name: Deploy Staging Frontend

on:
  push:
    tags:
      - "stg-*"
    paths:
      - ".github/workflows/deploy-staging-frontend.yml"
      - "frontend/**"
      - "data/*/ssr.json"

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Fullstack: install and build"
        run: |
          cd fullstack
          yarn
          yarn build
      - name: "Frontend Root: install and build"
        run: |
          cd frontend
          yarn
          yarn build
          yarn generate:sitemap
      - name: "Frontend Firebase: install"
        run: |
          cd frontend/firebase
          yarn
      - name: "Frontend Firebase: deploy"
        run: |
          cd frontend/firebase
          yarn deploy:staging
        env:
          CI: true
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
