name: Deploy Staging Web

on:
  push:
    tags:
      - "stg-v*"
    paths:
      - ".github/workflows/deploy-stg-web.yml"
      - "common/**"
      - "web/**"
      - "data/*/ssr.json"

jobs:
  Deploy-Stg-Web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install workspace dependencies"
        run: |
          yarn
      - name: "Build common directory"
        run: |
          cd common
          yarn build
      - name: "Deploy web"
        run: |
          cd web
          yarn deploy:stg

        env:
          CI: true
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
