name: Deploy To Production Environment

on:
  push:
    tags:
      - "v*"

jobs:
  Deploy-Web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install workspace dependencies"
        run: |
          yarn
      - name: "Build common directory"
        run: |
          cd common
          yarn build
      - name: "Deploy web"
        run: |
          cd web
          yarn deploy

        env:
          CI: true
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  Deploy-Data:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install workspace dependencies"
        run: |
          yarn
      - name: "Build common directory"
        run: |
          cd common
          yarn build
      - name: "Deploy data"
        run: |
          cd data
          yarn deploy

        env:
          CI: true
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  Deploy-Api:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install workspace dependencies"
        run: |
          yarn
      - name: "Build common directory"
        run: |
          cd common
          yarn build
      - name: "Build data directory"
        run: |
          cd data
          yarn build
      - name: "Deploy api"
        run: |
          cd api
          yarn deploy

        env:
          CI: true
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          SSH_ADDRESS_PRD: ${{ secrets.SSH_ADDRESS_PRD }}
