name: Deploy To Stage Environment

on:
  push:
    tags:
      - "stg-v*"

jobs:
  Deploy-Web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install workspace dependencies"
        run: |
          yarn install --ignore-scripts
      - name: "Build common directory"
        run: |
          cd common
          yarn build
      - name: "Deploy web"
        run: |
          cd web
          yarn deploy:stg

        env:
          CI: true
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  Deploy-Data:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install workspace dependencies"
        run: |
          yarn install --ignore-scripts
      - name: "Build common directory"
        run: |
          cd common
          yarn build
      - name: "Deploy data"
        run: |
          cd data
          yarn deploy:stg

        env:
          CI: true
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  Deploy-Api:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install workspace dependencies"
        run: |
          yarn install --ignore-scripts
      - name: "Build common directory"
        run: |
          cd common
          yarn build
      - name: "Build data directory"
        run: |
          cd data
          yarn build
      - name: "Deploy api"
        run: |
          cd api
          yarn deploy:stg

        env:
          CI: true
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          SSH_ADDRESS_STG: ${{ secrets.SSH_ADDRESS_STG }}

  Deploy-Mobile:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}
      - name: "Install workspace dependencies"
        run: |
          yarn install --ignore-scripts
      - name: "Build common directory"
        run: |
          cd common
          yarn build
      - name: "Install mobile dependencies"
        run: |
          cd mobile
          yarn
      - name: "Deploy mobile"
        run: |
          cd mobile
          expo publish

        env:
          CI: true
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
